include:
  - component: gitlab.si.c-s.fr/to-be-continuous/mkdocs/gitlab-ci-mkdocs@2.5.1
    inputs:
      site-dir: "build/html"
  - component: gitlab.si.c-s.fr/to-be-continuous/gitleaks/gitlab-ci-gitleaks@2.5.2
  - component: gitlab.si.c-s.fr/space_platforms/metis/tools/ci-precommit/gitlab-ci-precommit@3.0.0
  - component: gitlab.si.c-s.fr/to-be-continuous/docker/gitlab-ci-docker@5.10.3
    inputs:
      build-args: "--build-arg VERSION=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA-$CI_JOB_STARTED_AT"
      prod-publish-strategy: "auto"
      hadolint-args: "--failure-threshold warning"
      trivy-security-level-threshold: "HIGH,CRITICAL"

stages:
  - build
  - test
  - package-build
  - package-test
  - infra
  - deploy
  - acceptance
  - publish
  - infra-prod
  - production
