# Project information
site_name: "SharingHub Docs"
site_description: "Documentation of the SharingHub."
copyright: "Copyright &copy; 2024, CS Group"

# Configuration
dev_addr: "127.0.0.1:5000"
site_dir: "build/html"
docs_dir: "src"
theme:
  name: material
  language: en
  features:
    - content.code.copy
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  logo: assets/img/logo-white.png
  favicon: assets/img/favicon.ico
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to light mode

# Extensions
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - footnotes
  - md_in_html
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: ["src"]
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true

# Plugins
plugins:
  - macros:
      render_by_default: false
  - search:
      lang: en
  - tags

# Page tree
nav:
  - Home: index.md
  - Explore:
      - explore/overview.md
      - Features:
          - explore/auth.md
          - Navigation:
              - explore/categories.md
              - explore/search.md
          - explore/project-view.md
          - explore/stac-api.md
  - Share:
      - share/overview.md
      - Metadata:
          - share/metadata/index.md
          - share/metadata/configuration.md
          - share/metadata/reference.md
          - Examples:
              - share/metadata/model-case.md
              - share/metadata/dataset-case.md
          - share/metadata/stac-concepts.md
      - Data:
          - share/data/index.md
          - Git LFS: share/data/git-lfs.md
          - DVC: share/data/dvc.md
  - Tutorials:
      - tutorials/manage_dataset_with_dvc.md
      - tutorials/manage_dataset_with_shell.md
  - Resources:
      - resources/architecture.md
      - resources/index.md
      - resources/ogc.md
      - resources/stac.md
  - Legal Notice:
      - legal/privacy.md

# Footer links
extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/csgroup-oss/sharinghub"
    - icon: fontawesome/solid/copyright
      link: "https://www.csgroup.eu"
